### ISSUE TITLE
Eenae review #1

### ISSUE THREAD

**Issue by Eenae** [mixbytes/boomstarter-ico#1]
- [x] в readme репозитория нужно сказать как собирать и тестировать
- [x] там же, стоит описать порядок действий в продакшне по деплою и оперированию контрактами

**BoomstarterToken**
- [x] предлагаю разрешать disablePrivileged только после thaw - чтобы не прострелили ногу
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterToken.sol#L177
функция, кажется, не нужна

**IBoomstarterToken**
- [x] не упомянуто thaw

**EthPriceDependent**
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/EthPriceDependent.sol#L42
классический баг с присваиванием m_ETHPriceUpdateRunning вместо сравнения. Сравнения с литералами лучше записывать в виде `literal == variable`, напр. `false == m_ETHPriceUpdateRunning` - тогда подобную ошибку найдет сам компилятор
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/EthPriceDependent.sol#L67
этот вызов пройдет? по-моему, забыто `m_ETHPriceUpdateRunning = false`
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/EthPriceDependent.sol#L47
логирование события стоит расположить после всех действий, которые могут "упасть"
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/EthPriceDependent.sol#L43
это выражение я бы вынес здесь и далее в отдельную функцию - меньше копипаста - меньше мест, которые могут "разойтись"
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/EthPriceDependent.sol#L100 наверное, нужно кинуть событие
- [x] если я правильно понимаю, нет возможности пополнить баланс эфира контракта - только дождаться когда он кончится и двойного `m_ETHPriceUpdateInterval` (default function будет "занята" в контрактах-наследниках)

**BoomstarterPresale**
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L203
хард кап - 1.5 млн, в 10 раз меньше
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L210
и в прочих местах, где используется 10**18 - точно можно обойтись без приведения к uint и не будет усечения?
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L174
не используется
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L177
не используется
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L69
я бы добавил проверку, что курс доллара уже получен
- [x] https://github.com/mixbytes/boomstarter-ico/blob/bce5d2d67668a2ec35c7e9efa9a836523d1ed4ad/contracts/BoomstarterPresale.sol#L166
уже есть в родительском контракте

**Comment by Eenae** [comment]
Кстати, 30000 * 100 не будет усечено?

> Check that bridge is set to true in "contracts/EthPriceDependent.sol" constructor:

Правки кода в ходе тестирования или деплоя я бы избегал - для нужд тестирования можно сделать контракт-наследник, в котором параметры переопределяются нужным образом.

**Comment by Eugenpaul** [comment]
@Eenae Переделано в eeb08cd4a698812f98fd8d58425f1e293d3d306
